### ISSUE TITLE
这个输入框及富文本显示控件的扩展思路是什么

### ISSUE THREAD

**Issue by czronaldo11** [hyz1992/rich_textfield#2]
请教几个问题 <~>:
1.输入框的扩展思路是什么,有什么基础控件参考不?
2.富文本您这边也是基于字节跳动的改的么?后来扩展的原因和思路是什么?
3.我看输入框这边的图片占位符由"\u200B"替换为了一个汉字,当时这么做的原因是啥?

**Comment by hyz1992** [comment]
1.基本是基于官方的TextField修改的，stable1.0.0
2.emoji部分是用的字节跳动的思路，我的项目需要输入框能输入自定义表情，找不到现成的，只能自己扩展
3.因为“\u200b”没有宽度，删除以及长按复制的时候textPaniter计算索引以及选中长度会出问题，所以就用一个生僻字代替了
