### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by linguitang** [hyz1992/rich_textfield#4]
1、表情的话，通过controller传入表情列表
```
Map<String, String> emojis = {
"[强]":"resUrl",
"[微笑]":"resUrl",
}
```
只要文本变化时正则匹配到"\\[[\u4e00-\u9fa5]+]"就尝试认为是一个表情，把这个匹配字符串拿去表情列表里匹配一下，匹配得到就可以显示表情，类似我只要文本输入"[强]"就可以显示表情了，复制的时候也允许复制得到"[强]"字符串。这个做法有点类似微信

2、可以考虑处理一下，允许插入大图（比如相册图片）
3、可以在非编辑状态的时候允许复制，这样就可以抛弃字节跳动的那个richtext了，单纯要显示的时候，只要把这个控件设置成只读就可以了
4、表情最好分成系统表情和普通表情，系统表情正常资源是在本地，普通表情正常资源是在网上

**Comment by hyz1992** [comment]
目前的实现确实不太友好，有时间我再优化一下。
